---

- name: Install Nginx on Ubuntu and CentOS
  hosts: nginx
  become: yes 
  tasks:

    - name: Install Nginx (Ubuntu)
      apt:
        name: nginx
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Nginx (CentOS)
      yum:
        name: nginx
        state: present
      when: ansible_os_family == "RedHat"
